let fruit123:string[]=["1", "One", "Tarkesh"];
console.log(fruit123);
let fruits123:Array<string> = ["One", "Two", "Three"];
console.log(fruits123);
let myarray=[1,true,false, "Dr. Tarkeshwar", {'name':'Tarkesh', 'phone':'454545', }];
console.log(myarray);
let scores:Array<number> =[1,2,4,56,6,4];
console.log(scores);
let scores1:Array<number>;
scores1=[6,8,5,8,4,6,78];
console.log(scores1);
let strOrNumber:(string|number)[]=[3,"name","address",555];
console.log(strOrNumber);
let strOrNumber1:Array<string|number>=[3,"name","address",555];
console.log(strOrNumber1);
let employee:[number,string]=[1,"Tarkesh"];
//let employee1:[number,string]=["Tarkesh",3];
console.log(employee);